apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DB_NAME
          value: "VOTACION"
        - name: DB_USER
          value: "db2inst1"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db2-secret
              key: db2-password
        - name: DB_HOST
          value: "db2-service"
        - name: DB_PORT
          value: "50000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001       # Puerto expuesto dentro del cluster
      targetPort: 3000 



