apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db2
  template:
    metadata:
      labels:
        app: db2
    spec:
      containers:
      - name: db2
        image: ibmcom/db2:11.5.8.0
        ports:
        - containerPort: 50000
        env:
        - name: LICENSE
          value: "accept"
        - name: DB2INSTANCE
          value: "db2inst1"
        - name: DB2INST1_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db2-secret
              key: db2-password
        - name: DBNAME
          value: "VOTACION"
        - name: PERSISTENT_HOME
          value: "true"
        volumeMounts:
        - name: db2-storage
          mountPath: /database
      volumes:
      - name: db2-storage
        persistentVolumeClaim:
          claimName: db2-pvc
